'use client';

import { Sandpack } from '@codesandbox/sandpack-react';
import { motion } from 'framer-motion';
import { Rocket, Sparkles } from 'lucide-react';

interface SandpackPreviewProps {
    files: Record<string, string>;
    onReady?: () => void;
}

export function SandpackPreview({ files, onReady }: SandpackPreviewProps) {
    // Convert files to Sandpack format
    const sandpackFiles: Record<string, string> = {};

    for (const [path, content] of Object.entries(files)) {
        let targetPath = path;

        // Normalize paths
        if (path === 'App.tsx' || path === '/App.tsx') {
            targetPath = '/App.tsx';
        } else if (!path.startsWith('/')) {
            targetPath = '/' + path;
        }

        sandpackFiles[targetPath] = content;
    }

    // If no files, show empty state
    if (Object.keys(sandpackFiles).length === 0) {
        return (
            <div className="h-full flex items-center justify-center bg-gradient-to-br from-zinc-950 via-zinc-900 to-zinc-950 text-white p-8">
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="text-center max-w-md"
                >
                    <motion.div
                        initial={{ scale: 0.8, opacity: 0 }}
                        animate={{ scale: 1, opacity: 1 }}
                        transition={{ delay: 0.1 }}
                        className="text-7xl mb-6"
                    >
                        <div className="inline-flex items-center justify-center w-24 h-24 rounded-2xl bg-gradient-to-br from-indigo-500/20 to-purple-500/20 border border-indigo-500/30">
                            <Rocket className="w-12 h-12 text-indigo-400" />
                        </div>
                    </motion.div>
                    <motion.h3
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: 0.2 }}
                        className="text-2xl font-bold mb-3 bg-gradient-to-r from-white to-zinc-400 bg-clip-text text-transparent"
                    >
                        Ready to Build
                    </motion.h3>
                    <motion.p
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: 0.3 }}
                        className="text-zinc-400 mb-6"
                    >
                        Describe your app idea in the chat and click <span className="text-indigo-400 font-medium">"Generate App"</span> to see it come to life!
                    </motion.p>
                    <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        transition={{ delay: 0.5 }}
                        className="flex items-center justify-center gap-2 text-sm text-zinc-500"
                    >
                        <Sparkles className="w-4 h-4 text-indigo-400" />
                        <span>Powered by AI</span>
                    </motion.div>
                </motion.div>
            </div>
        );
    }

    // Ensure we have an App.tsx file
    if (!sandpackFiles['/App.tsx']) {
        // Try to find any component file and use it as the main
        const componentFiles = Object.keys(sandpackFiles).filter(f => f.endsWith('.tsx'));

        if (componentFiles.length > 0) {
            // Find the most likely entry point
            const mainFile = componentFiles.find(f =>
                f.toLowerCase().includes('app') ||
                f.toLowerCase().includes('index') ||
                f.toLowerCase().includes('page')
            ) || componentFiles[0];

            const content = sandpackFiles[mainFile];

            // If it has a default export, use it as App.tsx
            if (content.includes('export default')) {
                sandpackFiles['/App.tsx'] = content;
            } else {
                // Create a wrapper
                sandpackFiles['/App.tsx'] = `export default function App() {
  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-indigo-500 to-purple-600">
      <div className="text-center text-white">
        <h1 className="text-4xl font-bold mb-4">Your App</h1>
        <p className="text-xl opacity-80">Generated by Neura AI</p>
      </div>
    </div>
  );
}`;
            }
        } else {
            sandpackFiles['/App.tsx'] = `export default function App() {
  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-indigo-500 to-purple-600">
      <div className="text-center text-white">
        <h1 className="text-4xl font-bold mb-4">Welcome to Your App</h1>
        <p className="text-xl opacity-80">Generated by Neura AI</p>
      </div>
    </div>
  );
}`;
        }
    }

    // Ensure we have styles
    if (!sandpackFiles['/styles.css']) {
        sandpackFiles['/styles.css'] = `@tailwind base;
@tailwind components;
@tailwind utilities;

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}`;
    }

    return (
        <div className="h-full w-full bg-zinc-900">
            <Sandpack
                template="react-ts"
                theme="dark"
                files={sandpackFiles}
                options={{
                    showNavigator: false,
                    showTabs: true,
                    showLineNumbers: true,
                    showInlineErrors: true,
                    wrapContent: true,
                    editorHeight: '100%',
                    editorWidthPercentage: 50,
                    autorun: true,
                    autoReload: true,
                    recompileMode: 'delayed',
                    recompileDelay: 500,
                }}
                customSetup={{
                    dependencies: {
                        // UI & Icons
                        'lucide-react': '^0.460.0',

                        // Animations
                        'framer-motion': '^11.11.17',

                        // 3D (if needed)
                        'three': '^0.170.0',
                        '@react-three/fiber': '^8.17.10',
                        '@react-three/drei': '^9.117.3',

                        // State management
                        'zustand': '^4.5.0',

                        // Utilities
                        'clsx': '^2.1.0',
                        'date-fns': '^3.0.0',

                        // Charts (if needed)
                        'recharts': '^2.12.0',

                        // Forms
                        'react-hook-form': '^7.49.0',
                    },
                }}
            />
        </div>
    );
}
