import { NextRequest, NextResponse } from 'next/server';
import { getServerSupabase, isSupabaseConfigured } from '@/lib/supabase/client';
import { ApiError } from '@/lib/types/app';
import archiver from 'archiver';

type RouteParams = { params: Promise<{ id: string }> };

// GET /api/projects/[id]/zip - Download project as ZIP
export async function GET(request: NextRequest, { params }: RouteParams) {
    try {
        const { id } = await params;

        if (!isSupabaseConfigured) {
            return NextResponse.json<ApiError>(
                { error: 'Database not configured' },
                { status: 503 }
            );
        }

        const supabase = getServerSupabase()!;

        // Fetch project
        const { data: project, error: projectError } = await supabase
            .from('projects')
            .select('id, name, spec')
            .eq('id', id)
            .single();

        if (projectError || !project) {
            return NextResponse.json<ApiError>(
                { error: 'Project not found' },
                { status: 404 }
            );
        }

        // Fetch project files
        const { data: files, error: filesError } = await supabase
            .from('project_files')
            .select('path, content')
            .eq('project_id', id);

        if (filesError || !files || files.length === 0) {
            return NextResponse.json<ApiError>(
                { error: 'No files found for this project' },
                { status: 404 }
            );
        }

        // Create ZIP archive
        const archive = archiver('zip', {
            zlib: { level: 9 },
        });

        // Add package.json
        const packageJson = {
            name: project.name.toLowerCase().replace(/\s+/g, '-'),
            version: '0.1.0',
            private: true,
            scripts: {
                dev: 'next dev',
                build: 'next build',
                start: 'next start',
                lint: 'next lint',
            },
            dependencies: {
                next: '^15.0.0',
                react: '^19.0.0',
                'react-dom': '^19.0.0',
                '@supabase/supabase-js': '^2.45.0',
                'lucide-react': '^0.460.0',
            },
            devDependencies: {
                typescript: '^5.0.0',
                '@types/node': '^20.0.0',
                '@types/react': '^19.0.0',
                '@types/react-dom': '^19.0.0',
                tailwindcss: '^3.4.0',
                postcss: '^8.0.0',
                autoprefixer: '^10.0.0',
            },
        };
        archive.append(JSON.stringify(packageJson, null, 2), { name: 'package.json' });

        // Add tsconfig.json
        const tsConfig = {
            compilerOptions: {
                lib: ['dom', 'dom.iterable', 'esnext'],
                allowJs: true,
                skipLibCheck: true,
                strict: true,
                noEmit: true,
                esModuleInterop: true,
                module: 'esnext',
                moduleResolution: 'bundler',
                resolveJsonModule: true,
                isolatedModules: true,
                jsx: 'preserve',
                incremental: true,
                plugins: [{ name: 'next' }],
                paths: {
                    '@/*': ['./src/*'],
                },
            },
            include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
            exclude: ['node_modules'],
        };
        archive.append(JSON.stringify(tsConfig, null, 2), { name: 'tsconfig.json' });

        // Add tailwind.config.js
        const tailwindConfig = `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
`;
        archive.append(tailwindConfig, { name: 'tailwind.config.js' });

        // Add postcss.config.js
        const postcssConfig = `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`;
        archive.append(postcssConfig, { name: 'postcss.config.js' });

        // Add next.config.js
        const nextConfig = `/** @type {import('next').NextConfig} */
const nextConfig = {};
module.exports = nextConfig;
`;
        archive.append(nextConfig, { name: 'next.config.js' });

        // Add .env.example
        const envExample = `NEXT_PUBLIC_SUPABASE_URL=your_supabase_url
NEXT_PUBLIC_SUPABASE_ANON_KEY=your_supabase_anon_key
SUPABASE_SERVICE_ROLE_KEY=your_supabase_service_role_key
`;
        archive.append(envExample, { name: '.env.example' });

        // Add README
        const readme = `# ${project.name}

Generated by Neura AI App Builder.

## Setup

1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

2. Copy \`.env.example\` to \`.env.local\` and fill in your Supabase credentials.

3. Run the development server:
   \`\`\`bash
   npm run dev
   \`\`\`

4. Open [http://localhost:3000](http://localhost:3000) in your browser.

## App Specification

\`\`\`json
${JSON.stringify(project.spec, null, 2)}
\`\`\`
`;
        archive.append(readme, { name: 'README.md' });

        // Add project files
        for (const file of files) {
            // Ensure path is within src/ directory
            const filePath = file.path.startsWith('src/') ? file.path : `src/${file.path}`;
            archive.append(file.content, { name: filePath });
        }

        // Finalize archive
        archive.finalize();

        // Convert archive stream to ReadableStream
        const chunks: Uint8Array[] = [];

        await new Promise<void>((resolve, reject) => {
            archive.on('data', (chunk) => chunks.push(chunk));
            archive.on('end', () => resolve());
            archive.on('error', reject);
        });

        const zipBuffer = Buffer.concat(chunks);

        // Return ZIP file
        const filename = `${project.name.toLowerCase().replace(/\s+/g, '-')}.zip`;

        return new NextResponse(zipBuffer, {
            status: 200,
            headers: {
                'Content-Type': 'application/zip',
                'Content-Disposition': `attachment; filename="${filename}"`,
                'Content-Length': zipBuffer.length.toString(),
            },
        });

    } catch (error) {
        console.error('ZIP export error:', error);
        return NextResponse.json<ApiError>(
            { error: 'Failed to export project' },
            { status: 500 }
        );
    }
}
